name: Windows Test

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        version: [latest, branch@master, branch@dev]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@master
        with:
          xmake-version: ${{ matrix.version }}
      - name: Run tests in debug version
        run: |
          xmake --version
          xmake f -m debug -y
          xmake
          xmake run test_py2cpp
