name: macOS Test

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
        version: [latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@master
        with:
          xmake-version: ${{ matrix.version }}
      - name: Run tests
        run: |
          git submodule update --init
          xmake --version
          xmake f -m release -y
          xmake
          xmake run test_netoptim
